[package]
name = "dns2socks"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive", "wrap_help"] }
ctrlc2 = { version = "3.5", features = ["tokio", "termination"] }
dotenvy = "0.15"
env_logger = "0.11"
log = "0.4"
moka = { version = "0.12", features = ["future"] }
rand = "0.8"
socks5-impl = "0.5"
tokio = { version = "1.36", features = ["full"] }
trust-dns-proto = "0.23"
