language = "C"
cpp_compat = true

[export]
include = ["dns2socks_start", "dns2socks_stop", "dns2socks_set_log_callback"]
exclude = []

[export.rename]
"ArgVerbosity" = "Dns2socksVerbosity"

[enum]
prefix_with_name = true
